### ISSUE TITLE
Could not find class nodejs::v0_10_X

### ISSUE THREAD

**Issue by gabrielf** [boxen/puppet-nodejs#13]
Hi, I'm trying to install a version of nodejs that there is not yet a manifest for in this module. I get the impression that this should be possible by adding:

> nodejs::version { 'v0.10.10': }

to site.pp but instead I get the error

> Could not find class nodejs::v0_10_10 for mybox.local on node mybox.local

I've tried updating all modules in Puppetfile to the latest tags but with the same result. Is my assumption that this should work wrong?

**Comment by cregev** [comment]
did you  resolve it ?

**Comment by blackjid** [comment]
I think this issue got deprecated after the latest rewrite. There are no manifests now, any version that is supported by `node-build` should be installable.

**Comment by blackjid** [comment]
Please feel free to reopen if needed!
