### ISSUE TITLE
nodenv rehash and node global modules

### ISSUE THREAD

**Issue by jlord** [boxen/puppet-nodejs#23]
It's a common thing to install global modules with node (there are scripts you just want to execute from the command line as utilities). In Node it is expected that a user can type:

```
npm install -g niceModule
niceModule
```

Currently with nodenv when you globally install a module you need to run `nodenv rehash` to be able to run the module as expected (and commonly documented by the modules).

It would nice to either have `nodenv rehash` automatically run so that users aren't tripped up and things work as expected or to try using something like the [nave](https://npmjs.org/package/nave) module, which is commonly used for versioning node in the community. 

@wfarr I'm happy to talk about this more/help out!

**Comment by farhadahmed** [comment]
I'm still not sure I understand what `nodenv rehash` does.  Why do we need to run this in order to have a module run as expected?
