### ISSUE TITLE
How to update node-build definitions?

### ISSUE THREAD

**Issue by stereobooster** [boxen/puppet-nodejs#53]
```
/opt/boxen/node-build/bin/node-build --definitions
...
iojs-1.6.2
iojs-1.x-dev
```

And node-build provides iojs-3.0.0. io.js it self has reached 3.2.0

**Comment by blackjid** [comment]
you can run `node /opt/boxen/node-build/tools/scraper.js`

that is part of `node-build` https://github.com/OiNutter/node-build#update-available-build-versions

**Comment by stereobooster** [comment]
```
node /opt/boxen/node-build/tools/scraper.js
Updating node versions
Updating iojs versions
{ [Error: ENOENT: no such file or directory, open '../share/node-build/0.10.16']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '../share/node-build/0.10.16' }
```

**Comment by blackjid** [comment]
that's weird, it works for me....
Have you tried to update the latest `node-build` in using hiera?? that way you should be able to install the latest versions of iojs. That version also have the newly released `node v4.0.0`

```yml
nodejs::build::ensure: '80cb791b63debce35110b55590cf3b9f953d72db'
```

**Comment by habitullence** [comment]
I get the same errors as @stereobooster.

**Comment by blackjid** [comment]
Closing, feel free to open again if needed
